### ISSUE TITLE
사파리에서 홈화면에 추가하여 사용 시 카메라가 켜지지 않음

### ISSUE THREAD

**Issue by cmygray** [NullFull/isnamyang#13]
페이스북 메시지로 제보받은 내용입니다.

**Comment by cmygray** [comment]
관련 내용:
https://stackoverflow.com/questions/46228218/how-to-access-camera-on-ios11-home-screen-web-app

**Comment by cmygray** [comment]
https://bugs.webkit.org/show_bug.cgi?id=185448#c20

**Comment by cmygray** [comment]
https://github.com/NullFull/isnamyang/commit/f41830e7086e8c112b2af9199c8306ae840f159c

**Comment by cmygray** [comment]
iOS safari 에서는 fullscreen mode를, 그 외엔 standalone 모드를 사용하기 위해서:
* gatsby-plugin-manifest 제거
* manifest.json 을 정적 파일로 두 개 생성
* ua에 따라 각각 다른 경로로 manifest.json 요청
일케 하면 어떨까요? 플러그인 설정으로는 도무지 해결을 못하겠네요 =_=

**Comment by lexifdev** [comment]
UA에 따라 다른 Manifest를 보내려면 서버단 처리가 필요하겠군요 ㅠ gatsby 자체를 버려야 하는 상황

**Comment by cmygray** [comment]
link 요소를 바꿔치기 해도 소용이 없을까요?

**Comment by lexifdev** [comment]
js로 DOM을 조작하기 이전에 이미 읽어올 듯 한데요.

https://medium.com/@alshakero/how-to-setup-your-web-app-manifest-dynamically-using-javascript-f7fbee899a61

이런 방법도 있다고 하네요.

**Comment by cmygray** [comment]
https://github.com/NullFull/isnamyang/commit/5ee3ba7a9cc25984d33b95949482c5189cdb872b
