### ISSUE TITLE
검색이 안되요

### ISSUE THREAD

**Issue by lexifdev** [NullFull/isnamyang#16]
구글에서 '남양유없'을 검색해도 언급한 사이트만 걸리고 이 사이트가 안걸립니다.
helmet에 적절한 meta 내용을 넣을 필요가 있어 보입니다.

**Comment by cmygray** [comment]
title은 있고 description만 없어요

![image](https://user-images.githubusercontent.com/26966551/65221685-79b28d00-daf8-11e9-875f-2521bc9ec69d.png)

**Comment by welikeheon** [comment]
@lexfidev 혹시 구글에 등록은 하셨나요?
![스크린샷 2019-09-29 오전 12 26 55](https://user-images.githubusercontent.com/8732888/65818774-e42da080-e24f-11e9-9bf9-14b01ea8bdbd.png)

site: 로 치니까 나타나기는 하는데..
