### ISSUE TITLE
디스코드 봇으로 옮기기

### ISSUE THREAD

**Issue by ohahohah** [NullFull/isnamyang#77]
신고내용 알려주는 봇을 슬랙에서 디스코드로 옮겨야합니다

https://github.com/NullFull/isnamyang/blob/main/frontend/scripts/checkNewReport.js

**Comment by constmoon** [comment]
https://github.com/NullFull/isnamyang/commit/4832fe476e1d1b11c6449e64684dd0871b750a23 에서 작업 완료되어 close 합니다
